# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
   include:
     - main
     - dev
     - develop
  paths:
    include:
      - src/infra.net/Infra.Net.CacheManager/Infra.Net.CacheManager.csproj

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
#- script: dotnet build --configuration $(buildConfiguration)
#  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'restore'
  inputs:
    command: 'restore'
    projects: 'src/infra.net/Infra.Net.CacheManager/Infra.Net.CacheManager.csproj'
    arguments: '-v d'
    feedsToUse: 'select'
    vstsFeed: '27a5d52e-704b-436b-90a4-e31ee9bcbe49/72b8efd8-6405-44f9-ace8-4c9b4967ae26'

- task: DotNetCoreCLI@2
  displayName: 'build'
  inputs:
    command: 'build'
    projects: 'src/infra.net/Infra.Net.CacheManager/Infra.Net.CacheManager.csproj'
    arguments: '-v d --no-restore'
    
- task: NuGetCommand@2
  displayName: 'push'
  inputs:
    command: 'push'
    packagesToPush: '$(System.DefaultWorkingDirectory)/**/*.nupkg;!$(System.DefaultWorkingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'nuget.org'
