# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
   include:
     - main
     - dev
     - develop

pool:
  vmImage: windows-2022

variables:
  buildConfiguration: 'Release'

steps:
#- script: dotnet build --configuration $(buildConfiguration)
#  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'restore'
  inputs:
    command: 'restore'
    projects: 'src/**/*.csproj'
    arguments: '-v n'
    feedsToUse: 'select'
    vstsFeed: '27a5d52e-704b-436b-90a4-e31ee9bcbe49/72b8efd8-6405-44f9-ace8-4c9b4967ae26'

- task: DotNetCoreCLI@2
  displayName: 'build'
  inputs:
    command: 'build'
    projects: 'src/infra.net/**/*.csproj'
    arguments: '-v n --no-restore'
  
- task: DotNetCoreCLI@2
  displayName: 'tests'
  inputs:
    command: 'test'
    projects: 'src/UnitTests/**/*Tests.csproj'
    arguments: '-v n --no-restore'
  
